// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM-x5JJ4CbLo9Rc3EnkbfHwsPohgOZBqE',
    appId: '1:683053684468:web:8b603b8230808fe1f2f0a1',
    messagingSenderId: '683053684468',
    projectId: 'the-angry-planet',
    authDomain: 'the-angry-planet.firebaseapp.com',
    storageBucket: 'the-angry-planet.firebasestorage.app',
    measurementId: 'G-QB99Y19HBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyZ6s8_AUXmJNxLhOSd8BvIdOoyncyGLI',
    appId: '1:683053684468:android:ad161711a554d532f2f0a1',
    messagingSenderId: '683053684468',
    projectId: 'the-angry-planet',
    storageBucket: 'the-angry-planet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi6j4mUPyxrS5WWYmi93_eipStZ4xiTZo',
    appId: '1:683053684468:ios:4af2cc5f2d1c6d35f2f0a1',
    messagingSenderId: '683053684468',
    projectId: 'the-angry-planet',
    storageBucket: 'the-angry-planet.firebasestorage.app',
    iosBundleId: 'com.example.angryPlanet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi6j4mUPyxrS5WWYmi93_eipStZ4xiTZo',
    appId: '1:683053684468:ios:4af2cc5f2d1c6d35f2f0a1',
    messagingSenderId: '683053684468',
    projectId: 'the-angry-planet',
    storageBucket: 'the-angry-planet.firebasestorage.app',
    iosBundleId: 'com.example.angryPlanet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM-x5JJ4CbLo9Rc3EnkbfHwsPohgOZBqE',
    appId: '1:683053684468:web:83b8e184f220108df2f0a1',
    messagingSenderId: '683053684468',
    projectId: 'the-angry-planet',
    authDomain: 'the-angry-planet.firebaseapp.com',
    storageBucket: 'the-angry-planet.firebasestorage.app',
    measurementId: 'G-MX6YVEK2Q7',
  );
}
